/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppShoppingRouteImport } from './routes/_app/shopping'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppRecipesIndexRouteImport } from './routes/_app/recipes.index'
import { Route as AppCollectionsIndexRouteImport } from './routes/_app/collections.index'
import { Route as ApiUploadImageRouteImport } from './routes/api/upload/image'
import { Route as ApiImagesNameRouteImport } from './routes/api/images/$name'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AppRecipesNewRouteImport } from './routes/_app/recipes.new'
import { Route as AppRecipesIdRouteImport } from './routes/_app/recipes.$id'
import { Route as AppCollectionsIdRouteImport } from './routes/_app/collections.$id'
import { Route as AppRecipesIdEditRouteImport } from './routes/_app/recipes.$id_.edit'
import { Route as AppRecipesIdCookRouteImport } from './routes/_app/recipes.$id_.cook'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppShoppingRoute = AppShoppingRouteImport.update({
  id: '/shopping',
  path: '/shopping',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIndexRoute = AppRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIndexRoute = AppCollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => AppRoute,
} as any)
const ApiUploadImageRoute = ApiUploadImageRouteImport.update({
  id: '/api/upload/image',
  path: '/api/upload/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImagesNameRoute = ApiImagesNameRouteImport.update({
  id: '/api/images/$name',
  path: '/api/images/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRecipesNewRoute = AppRecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdRoute = AppRecipesIdRouteImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsIdRoute = AppCollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdEditRoute = AppRecipesIdEditRouteImport.update({
  id: '/recipes/$id_/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesIdCookRoute = AppRecipesIdCookRouteImport.update({
  id: '/recipes/$id_/cook',
  path: '/recipes/$id/cook',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/shopping': typeof AppShoppingRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$name': typeof ApiImagesNameRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/collections/': typeof AppCollectionsIndexRoute
  '/recipes/': typeof AppRecipesIndexRoute
  '/recipes/$id/cook': typeof AppRecipesIdCookRoute
  '/recipes/$id/edit': typeof AppRecipesIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/import': typeof AppImportRoute
  '/shopping': typeof AppShoppingRoute
  '/': typeof AppIndexRoute
  '/collections/$id': typeof AppCollectionsIdRoute
  '/recipes/$id': typeof AppRecipesIdRoute
  '/recipes/new': typeof AppRecipesNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$name': typeof ApiImagesNameRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/collections': typeof AppCollectionsIndexRoute
  '/recipes': typeof AppRecipesIndexRoute
  '/recipes/$id/cook': typeof AppRecipesIdCookRoute
  '/recipes/$id/edit': typeof AppRecipesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/import': typeof AppImportRoute
  '/_app/shopping': typeof AppShoppingRoute
  '/_app/': typeof AppIndexRoute
  '/_app/collections/$id': typeof AppCollectionsIdRoute
  '/_app/recipes/$id': typeof AppRecipesIdRoute
  '/_app/recipes/new': typeof AppRecipesNewRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/images/$name': typeof ApiImagesNameRoute
  '/api/upload/image': typeof ApiUploadImageRoute
  '/_app/collections/': typeof AppCollectionsIndexRoute
  '/_app/recipes/': typeof AppRecipesIndexRoute
  '/_app/recipes/$id_/cook': typeof AppRecipesIdCookRoute
  '/_app/recipes/$id_/edit': typeof AppRecipesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/import'
    | '/shopping'
    | '/collections/$id'
    | '/recipes/$id'
    | '/recipes/new'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$name'
    | '/api/upload/image'
    | '/collections/'
    | '/recipes/'
    | '/recipes/$id/cook'
    | '/recipes/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/import'
    | '/shopping'
    | '/'
    | '/collections/$id'
    | '/recipes/$id'
    | '/recipes/new'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$name'
    | '/api/upload/image'
    | '/collections'
    | '/recipes'
    | '/recipes/$id/cook'
    | '/recipes/$id/edit'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/import'
    | '/_app/shopping'
    | '/_app/'
    | '/_app/collections/$id'
    | '/_app/recipes/$id'
    | '/_app/recipes/new'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/images/$name'
    | '/api/upload/image'
    | '/_app/collections/'
    | '/_app/recipes/'
    | '/_app/recipes/$id_/cook'
    | '/_app/recipes/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiImagesNameRoute: typeof ApiImagesNameRoute
  ApiUploadImageRoute: typeof ApiUploadImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shopping': {
      id: '/_app/shopping'
      path: '/shopping'
      fullPath: '/shopping'
      preLoaderRoute: typeof AppShoppingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/': {
      id: '/_app/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AppRecipesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/': {
      id: '/_app/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof AppCollectionsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/upload/image': {
      id: '/api/upload/image'
      path: '/api/upload/image'
      fullPath: '/api/upload/image'
      preLoaderRoute: typeof ApiUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/images/$name': {
      id: '/api/images/$name'
      path: '/api/images/$name'
      fullPath: '/api/images/$name'
      preLoaderRoute: typeof ApiImagesNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/recipes/new': {
      id: '/_app/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof AppRecipesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id': {
      id: '/_app/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof AppRecipesIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections/$id': {
      id: '/_app/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof AppCollectionsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id_/edit': {
      id: '/_app/recipes/$id_/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof AppRecipesIdEditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipes/$id_/cook': {
      id: '/_app/recipes/$id_/cook'
      path: '/recipes/$id/cook'
      fullPath: '/recipes/$id/cook'
      preLoaderRoute: typeof AppRecipesIdCookRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppImportRoute: typeof AppImportRoute
  AppShoppingRoute: typeof AppShoppingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCollectionsIdRoute: typeof AppCollectionsIdRoute
  AppRecipesIdRoute: typeof AppRecipesIdRoute
  AppRecipesNewRoute: typeof AppRecipesNewRoute
  AppCollectionsIndexRoute: typeof AppCollectionsIndexRoute
  AppRecipesIndexRoute: typeof AppRecipesIndexRoute
  AppRecipesIdCookRoute: typeof AppRecipesIdCookRoute
  AppRecipesIdEditRoute: typeof AppRecipesIdEditRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppImportRoute: AppImportRoute,
  AppShoppingRoute: AppShoppingRoute,
  AppIndexRoute: AppIndexRoute,
  AppCollectionsIdRoute: AppCollectionsIdRoute,
  AppRecipesIdRoute: AppRecipesIdRoute,
  AppRecipesNewRoute: AppRecipesNewRoute,
  AppCollectionsIndexRoute: AppCollectionsIndexRoute,
  AppRecipesIndexRoute: AppRecipesIndexRoute,
  AppRecipesIdCookRoute: AppRecipesIdCookRoute,
  AppRecipesIdEditRoute: AppRecipesIdEditRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiImagesNameRoute: ApiImagesNameRoute,
  ApiUploadImageRoute: ApiUploadImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
